export { default as Piece } from './Piece/piece.component.jsx'
export { default as House } from './House/house.component.jsx'
export { default as Board } from './Board/board.component.jsx'
export { default as Header } from './Header/header.component.jsx'
export { default as TieModal } from './Modals/Tie/tie.component.jsx'
export { default as RenderTypes } from './Options/container/RenderTypes.jsx'